name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # stable tested version

      - name: Verify Flutter
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --verbose

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RajakDhobiSamajApp-APK
          path: build/app/outputs/flutter-apk/app-release.apk
